name: Branch Preview
description: Preview your latest changes on the branch on a sub domain
branding:
  icon: 'upload-cloud'
  color: 'red'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
